name: Generate Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configurar Git (pra conseguir commitar de volta)
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Gerar changelog com base nos commits
      - name: Generate changelog
        run: |
          # Cria o arquivo se não existir
          touch CHANGELOG.md

          # Pega o hash do último commit registrado no changelog
          LAST_COMMIT=$(grep -oP '\(\K[0-9a-f]{7}(?=\))' CHANGELOG.md | head -n 1)

          if [ -z "$LAST_COMMIT" ]; then
            git log --pretty=format:"- %s (%h)" > new_changelog.txt
          else
            git log $LAST_COMMIT..HEAD --pretty=format:"- %s (%h)" > new_changelog.txt
          fi

          # Acrescenta os novos commits no topo do changelog existente
          echo "## Changelog" > CHANGELOG.tmp
          cat new_changelog.txt >> CHANGELOG.tmp
          cat CHANGELOG.md >> CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push
