name: Generate Incremental Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # pega todo o histórico

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate incremental changelog
        run: |
          touch CHANGELOG.md
          
          # Pega todos os commits da branch, em ordem do mais antigo para o mais novo
          git log --reverse --pretty=format:"- %s (%h)" > all_commits.txt
          
          # Remove commits que já estão no CHANGELOG
          grep -Fxv -f CHANGELOG.md all_commits.txt > new_commits.txt
          
          # Se houver novos commits, adiciona no final do CHANGELOG
          if [ -s new_commits.txt ]; then
            echo "" >> CHANGELOG.md
            cat new_commits.txt >> CHANGELOG.md
          fi

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push
