name: Generate Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configurar Git (pra conseguir commitar de volta)
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Gerar changelog com base nos commits
      - name: Generate changelog
        run: |
          echo "## Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --pretty=format:"- %s (%h)" >> CHANGELOG.md

      # 4. Commitar arquivo atualizado
      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push
